### ISSUE TITLE
Diacritics.replace('Ž') returns: "Ž"

### ISSUE THREAD

**Issue by TennisVisuals** [mk7upurz87/jdu#1]
Apparently doesn't handle this character...

**Comment by mk7upurz87** [comment]
Do you know what it's derivative is?

**Comment by TennisVisuals** [comment]
Sorry, I don't understand the question... 
This is what I found: http://graphemica.com/%C5%BD


Meta
Unicode Code Point	U+017D
Script	Latin
Category	Uppercase Letter
Block	Latin Extended-A
HTML Entity (Decimal)	&#381;
HTML Entity (Hexadecimal)	&#x017D;
URL Escape Code	%C5%BD

**Comment by TennisVisuals** [comment]
I tested with node-diacritics and it works...
https://github.com/andrewrk/node-diacritics/blob/master/index.js

**Comment by mk7upurz87** [comment]
Makes sense, the character is there:

![screen shot 2017-05-30 at 9 32 21 am](https://cloud.githubusercontent.com/assets/1819361/26585715/f69b9d32-451a-11e7-8494-f12fa823a961.png)

**Comment by TennisVisuals** [comment]
yes, but the character is there in your code as well.
![screen shot 2017-05-30 at 3 34 37 pm](https://cloud.githubusercontent.com/assets/15993319/26585806/8be0a022-454d-11e7-8ea1-3d19f14a710f.jpg)

**Comment by TennisVisuals** [comment]
you know what... I could reproduce the error while other diacritics were properly replaced... then I did a hard reset of everything and the error disappeared.  Very mysterious.  Sorry to distract you from other things... If the error reappears I'll dig deeper before reaching out to you.

**Comment by mk7upurz87** [comment]
I was going to say I created a new test for it to reproduce and couldn't.  For good measure:

```
// ISSUE: https://github.com/mk7upurz87/jdu/issues/1
test('remove diacritics for Ž', () => {
    var original_char = 'Ž';
    var expected_char = 'Z';
    var translated_char = jdu.replace(original_char);
    console.log('starting with ' + original_char);
    console.log('translated as ' + translated_char);
    expect(translated_char).toEqual(expected_char);
});
```

```
$ jest
 PASS  test/jdu.test.js
  ✓ remove diacritics (3ms)
  ✓ isLatin (1ms)
  ✓ remove diacritics for Ž (1ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.948s, estimated 1s
Ran all test suites.
  console.log test/jdu.test.js:44
    starting with Ž

  console.log test/jdu.test.js:45
    translated as Z
```

**Comment by TennisVisuals** [comment]
Thanks for being so responsive!

**Comment by mk7upurz87** [comment]
Sure thing!
